### ISSUE TITLE
Requests 

### ISSUE THREAD

**Issue by ghost** [DarkTussin/LiteLock#1]
Hey @DarkTussin i love the application if i may can i suggest a few things?

Instead of having a GUI let the the application be a basic console application where user drops the folder he would like to encrypt over the LiteLock.exe a console window will open up and ask for password once password entered "Are you sure you would like to encrypt this folder Yes or No" on command yes zip up file and encrypt it. this very handy and light

**Comment by TyraelElDruin** [comment]
Hi @di48l069 thanks for the suggestion, but I'm not sure that anything is gained by using a console application over a GUI application. I can create a console version, but using drag and drop in a legitimate console is very cumbersome and hacky (See here: http://stackoverflow.com/questions/12662778/how-do-i-get-file-paths-of-items-dropped-onto-a-console-application-window).

One suggestion was to make a GUI application that looks like a console (console emulator), but at that point, it is still a GUI application and you're not gaining anything. Moreover, I'm not sure what would be gained by using a console application in general either. Saving a few kb?

After rereading, if you're suggesting that you just drag it directly onto the EXE itself, that might be something worth adding that would be relatively simple.

**Comment by ghost** [comment]
Hi @DarkTussin Yes i was suggesting 

> After rereading, if you're suggesting that you just drag it directly onto the EXE itself, that might be something worth adding that would be relatively simple.

Honestly will just look cool i'm not big fan of GUI sorry

**Comment by TyraelElDruin** [comment]
This functionality has been added in the latest release, however I don't think you will notice too much of a gain in speed and the GUI remains largely unchanged. You can now drag and drop files directly onto the EXE, select (by clicking) either Encrypt/Decrypt and enter your password. It will automatically close when it is complete, so it may be slightly faster, but I think a better solution is implementing context menus which I will add in the next release. I don't know if you'll be pleased because the GUI is still displayed and I don't think there's a good way around that unless you want no progress/messages/anything which seems like a bad idea.

If you don't like the look of the GUI, designing it to "look cool" by displaying some hacker gibberish might be something I would do out of boredom, but you might as well just make a batch file with the following code and run it instead of LiteLock.exe

```
@echo off
start cmd.exe /c "cd C:\ && dir *.* /s"
start cmd.exe /c "cd C:\ && dir *.* /s"
start cmd.exe /c "cd C:\ && dir *.* /s"
start cmd.exe /c "cd C:\ && dir *.* /s"
start LiteLock.exe
```

This will open four command windows with matrix-esque text that scrolls for quite some time (depending on how deep your C drive is) along with LiteLock. It's completely pointless, but it looks like this: http://i.imgur.com/N8lssMv.mp4

Not sure if that's what you're talking about or if you just want the whole thing to seem more hackerish. I suppose I could write a command version where you specify what individual file to encrypt and it displays a bitstream or something that looks interesting. Again, all of this being completely pointless for functionality. You might enjoy http://hackertyper.com/

**Comment by ghost** [comment]
:+1: Thanks
